config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root "searches#index"

  resources :searches, only: [:index, :new, :create, :show]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/search.rb
class Search < ApplicationRecord
  has_one_attached :file, dependent: :destroy
  has_many :search_results, dependent: :destroy

  enum text_area: { beginning: 'beginning', middle: 'middle', ending: 'ending' }
  enum text_percentage: (1..10).map { |i| "#{i * 10}" }

  validates_presence_of :phrases_size, :phrases_count, :text_area, :text_percentage

  validate :has_file_attached, :file_has_valid_type

  def decoded_file_content
    case file.content_type
    when 'text/plain'
      decode_content(file.download)
    when 'application/pdf'
      decode_content(pdf_file_content)
    end
  end

  def links_count
    search_results.sum { |result| result.links.count }
  end

  private

  def pdf_file_content
    temp_file = Tempfile.new('file.pdf')
    temp_file.binmode
    temp_file.write(file.blob.download)
    reader = PDF::Reader.new(temp_file)
    content = reader.pages.map(&:text).join("\n")
    temp_file.unlink
    content
  end

  def decode_content(content)
    content.encode(Encoding::UTF_8, "Windows-1252")
  rescue Encoding::UndefinedConversionError => e
    content.force_encoding(Encoding::UTF_8)
  end

  def has_file_attached
    unless file.attached?
      errors.add(:file, I18n.t('search.errors.file.empty'))
    end
  end

  def file_has_valid_type
    return unless file.attached?

    unless file.attachment.blob.content_type.in?(%w(text/plain application/pdf))
      errors.add(:file, I18n.t('search.errors.file.type'))
    end
  end
end

app/models/search_result.rb
class SearchResult < ApplicationRecord
  belongs_to :search

  validates_presence_of :search, :phrase
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/searches_controller.rb
class SearchesController < ApplicationController
  def index
    @searches = Search.order(updated_at: :desc).page(params[:page])
  end

  def new
    @search = Search.new(text_percentage: '50', text_area: 'beginning')
  end

  def create
    @search = Search.new(search_params)
    if @search.save
      create_search_results
      redirect_to searches_url, notice: I18n.t('searches.create.success')
    else
      render :new
    end
  end

  def show
    @search = Search.find(params[:id])
  end

private

  SERACH_PROCESSORS = [TextProcessors::ReferenceRemover,
    TextProcessors::TextReducer]

  def search_params
    params.require(:search).permit(:phrases_count, :phrases_size, :phrases_size,
      :text_percentage, :text_area, :file)
  end

  def processed_text
    search_params.delete(:file)

    SERACH_PROCESSORS.reduce(@search.decoded_file_content) do |text, processor|
      processor.new(text: text, options: search_params).perform
    end
  end

  def phrases_picker
    @phrases_picker ||= PhrasesPicker.new(text: processed_text, options: {
      phrases_count: @search.phrases_count, phrases_size: @search.phrases_size })
  end

  def create_search_results
    phrases_picker.perform.each do |phrase|
      links = FindLinks.new(phrase: phrase).from_azure

      SearchResult.create(phrase: phrase, search: @search, links: links)

      # Para evitar que exceda o limite máximo de requisições por segundo
      sleep 0.2
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/search_helper.rb
module SearchHelper
  def text_percentage_options_collection
    Search.text_percentages.map { |key, value| ["#{key} %", key] }
  end

  def text_area_options_collection
    Search.text_areas.map { |key, value| [I18n.t("search.text_area.#{key}"), key] }
  end

  def links_count_label(links_count)
    if links_count  == 0
      ""
    elsif links_count == 1
      " - 1 Link"
    else
      " - #{links_count} Links"
    end
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PlagFinder</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  </head>

  <body>
    <div class="container">
      <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav mr-auto">
            <li class="nav-item">
              <a class="nav-link" href="<%= root_url %>"><%= t('menu.home') %></a>
            </li>
          </ul>
        </div>
      </nav>
      <main class="col-12">
        <%= yield %>
      </main>
    </div>
  </body>
</html>

app/views/searches/index.html.erb
<div class="page-header mb-3 mt-3">
  <h1 class="bd-title d-inline-block"><%= t('searches.index.title') %></h1>
  <a href="<%= new_search_url %>" class="btn btn-primary float-right d-inline-block"><%= t('searches.index.new') %></a>
</div>

<% if flash[:notice] %>
  <%= render 'shared/alert', alert_class: 'success', alert_message: flash[:notice] %>
<% end %>

<% if @searches.count > 0 %>
  <table class="table">
    <thead>
      <tr>
        <th><%= t('search.date') %></th>
        <th><%= t('search.phrases_count') %></th>
        <th><%= t('search.phrases_size') %></th>
        <th><%= t('search.links_count') %></th>
        <th><%= t('search.text_percentage') %></th>
        <th><%= t('search.file') %></th>
      </tr>
    </thead>
    <tbody>
      <% @searches.each do |search| %>
        <tr>
          <td><a href="<%= search_url(search) %>"><%= search.created_at.strftime("%d/%m/%y às %H:%M")%></a></td>
          <td><%= "#{search.phrases_count} frases" %></td>
          <td><%= "#{search.phrases_size} palavras" %></td>
          <td><%= search.links_count %></td>
          <td><%= "#{search.text_percentage}%" %></td>
          <td><%= search.file.blob.filename %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
  <%= paginate @searches %>
<% else %>
  <%= render 'shared/alert', alert_class: 'secondary', alert_message: t('searches.index.empty') %>
<% end %>

app/views/searches/new.html.erb
<div class="page-header mb-3 mt-3">
  <h1 class="bd-title d-inline-block"><%= t('searches.new.title') %></h1>
</div>
<div class="lds-ring hidden"><div></div><div></div><div></div><div></div></div>
<div class="page-content">
  <%= form_for(@search, multipart: true, remote: true) do |form| %>
    <div class="form-group">
      <label for="search_file"><%= t('search.file') %></label>
      <%= form.file_field :file, class: "form-control-file" %>
    </div>
    <div class="form-group">
      <label for="search_phrases_size"><%= t('search.phrases_count') %></label>
      <%= form.text_field :phrases_count, class: 'form-control', placeholder: 'Digite o número de frases que serão selecionadas' %>
    </div>
    <div class="form-group">
      <label for="search_phrases_size"><%= t('search.phrases_size') %></label>
      <%= form.text_field :phrases_size, class: 'form-control', placeholder: 'Digite o número de palavras das frases que serão selecionadas' %>
    </div>
    <div class="form-group">
      <label for="search_text_percentage"><%= t('search.text_percentage') %></label>
      <%= form.select :text_percentage, text_percentage_options_collection, {}, class: 'form-control' %>
    </div>
    <div class="form-group">
      <label for="search_text_area"><%= t('search.text_area.title') %></label>
      <%= form.select :text_area, text_area_options_collection, {}, class: 'form-control' %>
    </div>

    <a href="<%= searches_url %>" class="btn btn-secondary"><%= t('searches.new.cancel') %></a>
    <%= form.submit t('searches.new.submit_button'), class: "btn btn-primary" %>
  <% end %>
</div>

app/views/searches/show.html.erb
<div class="page-header mb-3 mt-3">
  <h1 class="bd-title d-inline-block"><%= t('searches.show.title') %></h1>
  <a href="<%= searches_url %>" class="btn btn-primary float-right d-inline-block"><%= t('back') %></a>
</div>
<div class="row mb-3 col-12">
  <strong><%= t('search.date') %>:</strong>&nbsp;<%= @search.created_at.strftime("%d/%m/%y às %H:%M") %>
</div>
<div class="row">
  <div id="accordion" class="col-12">
    <% @search.search_results.each do |search_result| %>
      <div class="card">
        <div class="card-header" id="heading-<%= search_result.id %>">
          <h5 class="mb-0">
            <button class="btn btn-link is-phrase" data-toggle="collapse" data-target="#collapse-<%= search_result.id %>" aria-expanded="true" aria-controls="collapse-<%= search_result.id %>">
              "<%= search_result.phrase %>"<%= links_count_label(search_result.links.count) %>
            </button>
            <button title="Copiar" type="button" name="button" class="btn btn-light btn-sm copy-phrase float-right">
              <%= image_tag('clipboard-regular.svg', width: 16, height: 16, class: 'icon') %>
            </button>
          </h5>
        </div>

        <div id="collapse-<%= search_result.id %>" class="collapse" aria-labelledby="heading-<%= search_result.id %>" data-parent="#accordion">
          <div class="card-body">
            <% if search_result.links.count > 0 %>
                <ul>
                  <% search_result.links.each do |link| %>
                    <li class="mt-1">
                      <a href="<%= link %>" target="_blank"><%= link %></a>
                      <button title="Copiar" type="button" name="button" class="btn btn-light btn-sm copy-link">
                        <%= image_tag('clipboard-regular.svg', width: 16, height: 16, class: 'icon') %>
                      </button>
                    </li>
                  <% end %>
                </ul>
            <% else %>
              <%= t('searches.show.empty_links') %>
            <% end %>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/shared/_alert.html.erb
<div class="alert alert-<%= alert_class %>" role="alert">
  <%= alert_message %>
</div>